#!/usr/bin/env python3
"""Clone vllm_args.sh and overlay TP/PP/DP/speculative/KV-cache-dtype flags."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

STRIP_FLAGS = {
    "-tp",
    "--tensor-parallel-size",
    "-pp",
    "--pipeline-parallel-size",
    "-dp",
    "--data-parallel-size",
    "--kv-cache-dtype",
    "--attention-backend",
    "--linear-backend",
}

KV_DTYPE_SUFFIX = {
    "fp8": "",
    "float16": "_kvf16",
    "int8_per_token_head": "_kvint8",
}

LEGACY_BACKEND_SUFFIXES = ("_flashinfer", "_humming")

DSPARK_MODEL = "RadixArk/Qwen3.8-27B-DSpark"
DSPARK_TOKENS = 7

STRIP_PREFIXES = (
    "--speculative_config.",
    "--speculative-config",
    "--speculative_config",
)


def parse_args_file(path: Path) -> list[str]:
    """Parse an args file using the same bash parser as run_vllm.sh."""
    path = path.resolve()
    script = r"""
set -euo pipefail
source "$1"
ARGS=()
parse_args_file "$2" ARGS
printf '%s\0' "${ARGS[@]}"
"""
    out = subprocess.check_output(
        ["bash", "-c", script, "overlay_args", str(ROOT / "parse_args.sh"), str(path)],
        cwd=str(ROOT),
    )
    if not out:
        return []
    parts = out.split(b"\0")
    return [p.decode("utf-8") for p in parts if p]


def pair_args(args: list[str]) -> list[tuple[str, str | None]]:
    pairs: list[tuple[str, str | None]] = []
    i = 0
    while i < len(args):
        flag = args[i]
        if i + 1 < len(args) and not args[i + 1].startswith("-"):
            pairs.append((flag, args[i + 1]))
            i += 2
        else:
            pairs.append((flag, None))
            i += 1
    return pairs


def should_strip(flag: str) -> bool:
    if flag in STRIP_FLAGS:
        return True
    return any(flag == p or flag.startswith(p) for p in STRIP_PREFIXES)


def shell_quote(value: str) -> str:
    if re.fullmatch(r"[A-Za-z0-9_./:=,+@%-]+", value):
        return value
    return "'" + value.replace("'", "'\"'\"'") + "'"


def write_args_file(pairs: list[tuple[str, str | None]], dest: Path) -> None:
    lines = [
        "# Generated by bench/overlay_args.py — do not edit.",
        "",
    ]
    for flag, value in pairs:
        if value is None:
            lines.append(flag)
        else:
            lines.append(f"{flag} {shell_quote(value)}")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def get_flag(pairs: list[tuple[str, str | None]], *names: str, default: str | None = None) -> str | None:
    lookup = set(names)
    for flag, value in pairs:
        if flag in lookup:
            return value
    return default


def overlay(
    base_path: Path,
    dest: Path,
    *,
    tp: int,
    pp: int,
    mtp_tokens: int = 0,
    dp: int = 1,
    kv_dtype: str = "fp8",
    spec_method: str = "off",
    spec_tokens: int | None = None,
) -> list[tuple[str, str | None]]:
    method = spec_method
    tokens = mtp_tokens if spec_tokens is None else spec_tokens
    if method == "off" and mtp_tokens > 0:
        method = "mtp"
        tokens = mtp_tokens
    pairs = [(f, v) for f, v in pair_args(parse_args_file(base_path)) if not should_strip(f)]
    pairs.append(("-tp", str(tp)))
    pairs.append(("-pp", str(pp)))
    if dp > 1:
        pairs.append(("-dp", str(dp)))
    pairs.append(("--kv-cache-dtype", kv_dtype))
    if method == "mtp" and tokens > 0:
        pairs.append(("--speculative_config.method", "mtp"))
        pairs.append(("--speculative_config.num_speculative_tokens", str(tokens)))
    elif method == "dspark":
        n = tokens if tokens > 0 else DSPARK_TOKENS
        pairs.append(("--speculative_config.model", DSPARK_MODEL))
        pairs.append(("--speculative_config.num_speculative_tokens", str(n)))
        pairs.append(("--speculative_config.method", "dspark"))
        pairs.append(("--speculative_config.draft_sample_method", "probabilistic"))
        pairs.append(("--speculative_config.rejection_sample_method", "block"))
    write_args_file(pairs, dest)
    return pairs


def config_id(
    tp: int,
    pp: int,
    mtp_tokens: int,
    dp: int = 1,
    kv_dtype: str = "fp8",
    spec_method: str = "off",
) -> str:
    if spec_method == "dspark":
        spec = "dspark"
    else:
        spec = "off" if mtp_tokens <= 0 else f"mtp{mtp_tokens}"
    dp_part = f"_dp{dp}" if dp > 1 else ""
    kv_part = KV_DTYPE_SUFFIX.get(kv_dtype)
    if kv_part is None:
        kv_part = "_" + kv_dtype.replace("-", "_")
    return f"tp{tp}_pp{pp}{dp_part}_{spec}{kv_part}"


def canonical_config_id(cid: str) -> str:
    """Map historical *_flashinfer / *_humming ids onto the current scheme."""
    for suf in LEGACY_BACKEND_SUFFIXES:
        if cid.endswith(suf):
            return cid[: -len(suf)]
    return cid


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", type=Path, default=ROOT / "vllm_args.sh")
    parser.add_argument("--dest", type=Path, required=True)
    parser.add_argument("--tp", type=int, required=True)
    parser.add_argument("--pp", type=int, required=True)
    parser.add_argument("--dp", type=int, default=1)
    parser.add_argument("--mtp", type=int, default=0, help="0 = MTP off, else num_speculative_tokens")
    parser.add_argument(
        "--spec-method",
        default="off",
        choices=("off", "mtp", "dspark"),
        help="Speculative method. dspark uses --mtp as token count if >0, else 7.",
    )
    parser.add_argument("--kv-dtype", default="fp8")
    args = parser.parse_args(argv)
    overlay(
        args.base,
        args.dest,
        tp=args.tp,
        pp=args.pp,
        mtp_tokens=args.mtp,
        dp=args.dp,
        kv_dtype=args.kv_dtype,
        spec_method=args.spec_method,
        spec_tokens=args.mtp if args.mtp > 0 else None,
    )
    print(f"wrote {args.dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
